#!/usr/bin/env python3
"""Write the site's colour and font tokens from the one file that defines them.

WHY GENERATED. FALCONAge draws pages in three places: the documentation site,
the one-page HTML report and the Quarto report. They carried four palettes
between them (the site's logo orange, the figures' Okabe-Ito, a blue report
accent and a green one), and nothing kept them in step. The interface colours
now live once, in the ``ui`` block of ``plot/colorscheme.yaml``; the reports
read that block at run time, and this script writes it out as SCSS variables
for the two site themes, which cannot read YAML.

Usage
-----
    python docs/build_tokens.py           # rewrite docs/_tokens.scss
    python docs/build_tokens.py --check   # fail if it is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "python" / "src" / "falconage" / "plot" / "colorscheme.yaml"
TARGET = ROOT / "docs" / "_tokens.scss"


def render() -> str:
    ui = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))["ui"]
    out = ["// GENERATED by docs/build_tokens.py from the `ui` block of",
           "// python/src/falconage/plot/colorscheme.yaml. Edit the YAML, not this",
           "// file: the next build reverts it. The reports read the same block.",
           ""]
    for mode in ("light", "dark"):
        for key, value in ui[mode].items():
            out.append(f"$falcon-{mode}-{key}: {value};")
        out.append("")
    out.append(f"$falcon-font-sans: {ui['font_sans']};")
    out.append(f"$falcon-font-mono: {ui['font_mono']};")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if docs/_tokens.scss is out of date")
    args = ap.parse_args(argv)
    text = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print("docs/_tokens.scss is stale; run docs/build_tokens.py")
            return 1
        print("docs/_tokens.scss is current")
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
