#!/usr/bin/env python3
"""Generate ``docs/gallery.qmd`` from the figures in ``test/output_figures/gallery``.

WHY THIS IS GENERATED. The interpretation of each figure already exists, once,
in ``colorscheme.yaml`` -- it is the ``description`` the figure itself prints
underneath the axes. Writing it a second time in a documentation page would put
two copies of one sentence in the repository, and the copy on the website would
be the one nobody regenerates. So the page is assembled from the PNGs plus the
same text the figures carry, which means the caption on the site and the caption
in the image cannot disagree.

The tracked copy of each figure stays where ``test/run_all.py`` writes it, under
``test/output_figures/gallery/``. Quarto will not include a resource from
outside its project directory, so this also stages a copy into
``docs/figures/gallery/`` -- derived, gitignored, and regenerated here rather
than maintained.

Usage
-----
    python docs/build_gallery.py           # write docs/gallery.qmd
    python docs/build_gallery.py --check   # fail if stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GALLERY = ROOT / "test" / "output_figures" / "gallery"
TARGET = HERE / "gallery.qmd"

BANNER = ("<!-- GENERATED by docs/build_gallery.py from test/output_figures/gallery.\n"
          "     Edit that script, colorscheme.yaml, or regenerate the figures. -->")

# Figures grouped the way somebody reads them, rather than alphabetically.
# A name absent from every group still appears, under "Other" -- silently
# dropping a figure is how the gallery stops being a gallery.
GROUPS = [
    ("Start here", ["clock_atlas"],
     "One figure for the question everyone actually has: which of these "
     "algorithms detects anything."),
    ("Is the clock calibrated", ["ba_vs_ca", "bland_altman", "calibration"],
     "Before any biology: does the prediction track chronological age, and "
     "where does it drift."),
    ("Age acceleration", ["acceleration_group", "acceleration_density",
                          "acceleration_heatmap", "forest"],
     "The residual after age is removed, by group and across studies."),
    ("Outcomes", ["kaplan_meier", "volcano"],
     "Whether acceleration predicts anything that happens to a person."),
    ("How the clocks relate", ["clock_corr", "clock_chord", "clock_radar",
                               "clock_pca"],
     "Twenty clocks are not twenty measurements. These show how much they "
     "share -- of their features, and of their answers."),
    ("Benchmarking", ["benchmark_bars", "benchmark_error_bias",
                      "benchmark_heatmap"],
     "AA1 and AA2 against the ComputAgeBench conditions, and the "
     "error-versus-bias tradeoff that decides the ranking."),
    ("Data quality", ["coverage_bar", "missingness", "beta_density",
                      "platform", "study"],
     "Drawn before the results, because a coverage problem invalidates "
     "everything after it."),
]

HEAD = """---
title: "Figure gallery"
subtitle: "Every figure the package draws, on real data, with what each one is for"
---

{banner}

Each of these is produced by `test/run_all.py` against the public test corpus
and copied into `test/output_figures/gallery/`. They are regenerated from the
code, so a figure here is what the current version actually draws -- not a
screenshot taken once.

The caption under each image is the same text the figure prints beneath its own
axes. There is one copy of it, in `colorscheme.yaml`, so the website and the
PNG cannot drift apart.

::: {{.callout-note}}
## Reproducing these

```bash
docker run --rm -v "$PWD:/work" -w /work falconage:1.1.0-cpu \\
  python test/run_all.py
```

Which dataset each figure comes from, and why that one was chosen, is recorded
in [SOURCES.md]({repo}/blob/main/test/output_figures/gallery/SOURCES.md).
:::

"""


def descriptions() -> dict[str, dict]:
    sys.path.insert(0, str(ROOT / "python" / "src"))
    from falconage.plot import spec

    return spec.load()["plots"]


def stage_images() -> int:
    """Copy the PNGs under docs/, because Quarto cannot reach above its root.

    The figures live in `test/output_figures/gallery/` and are tracked there --
    that is the copy a reader of the repository sees, and the one a diff
    reports when somebody edits the colour scheme. Quarto will not include a
    resource from outside its project directory, so the site needs its own
    copy. It is derived, so it is gitignored; only the original is tracked.
    """
    import shutil

    dest = HERE / "figures" / "gallery"
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)
    n = 0
    for png in sorted(GALLERY.glob("*.png")):
        shutil.copyfile(png, dest / png.name)
        n += 1
    return n


def render() -> str:
    plots = descriptions()
    present = {p.stem for p in GALLERY.glob("*.png")}

    out = [HEAD.format(banner=BANNER,
                       repo="https://github.com/bhagesh-h/FALCONAge")]
    shown: set[str] = set()

    for title, names, blurb in GROUPS:
        here = [n for n in names if n in present]
        if not here:
            continue
        out.append(f"## {title}\n")
        out.append(blurb + "\n")
        for name in here:
            shown.add(name)
            out.append(_figure(name, plots))

    rest = sorted(present - shown)
    if rest:
        out.append("## Other\n")
        out.append("Figures not yet placed in a section above.\n")
        for name in rest:
            out.append(_figure(name, plots))

    out.append(f"\n---\n\n{len(present)} figures. "
               "Every one is also written per dataset under "
               "`test/output_figures/<group>/<dataset>/` when the full corpus "
               "run is executed; the gallery keeps one representative of each "
               "type so a reader does not have to fetch 586 MB to see them.\n")
    return "\n".join(out)


def _figure(name: str, plots: dict) -> str:
    meta = plots.get(name, {})
    title = meta.get("title", name.replace("_", " ").capitalize())
    desc = " ".join((meta.get("description") or "").split())
    rel = f"figures/gallery/{name}.png"

    block = [f"### {title}\n", f"![{title}]({rel})\n"]
    if desc:
        block.append(f"{desc}\n")
    block.append(f"`plot.{name}()` in Python.\n")
    return "\n".join(block)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if docs/gallery.qmd is out of date")
    args = ap.parse_args(argv)

    if not GALLERY.exists():
        print(f"{GALLERY.relative_to(ROOT)} does not exist; run "
              "test/run_all.py first")
        return 1

    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale; run docs/build_gallery.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    staged = stage_images()
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)} and staged {staged} figure(s) "
          "into docs/figures/gallery")
    return 0


if __name__ == "__main__":
    sys.exit(main())
