#!/usr/bin/env python3
"""Generate ``r/NEWS.md`` from the shared ``CHANGELOG.md``.

WHY GENERATE IT. R users read `NEWS.md` and CRAN renders it; Python users and
everybody browsing the repository read `CHANGELOG.md`. Both describe the same
release, because the R package delegates every number to the Python core -- a
change to either is a change to both. Two hand-maintained files describing one
release disagree within a version, and the disagreement is invisible until
somebody quotes the wrong one.

WHAT CHANGES IN TRANSLATION. R's NEWS convention wants `# <Package> <version>`
as the version heading and short bulleted sections under it, which is close
enough to Keep a Changelog that the transformation is mechanical:

  ``## [1.0.0] - 2026-08-08``  ->  ``# FALCONAge 1.0.0``
  ``## [Unreleased]``          ->  ``# FALCONAge (development version)``
  ``### Fixed``                ->  ``## Fixed``

Link-reference definitions at the foot are dropped, since NEWS.md is rendered
standalone and a dangling `[1.0.0]: <url>` block is noise in `news()` output.

Usage
-----
    python docs/build_news.py           # write r/NEWS.md
    python docs/build_news.py --check   # exit non-zero if it is stale (for CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "CHANGELOG.md"
TARGET = ROOT / "r" / "NEWS.md"
PACKAGE = "FALCONAge"

BANNER = ("<!-- GENERATED by docs/build_news.py from CHANGELOG.md.\n"
          "     Edit the changelog, not this file -- the next build reverts it. -->\n\n")

VERSION = re.compile(r"^## \[([^\]]+)\](?:\s*[-–—]\s*(.+))?$")
SECTION = re.compile(r"^### (.+)$")
LINKDEF = re.compile(r"^\[[^\]]+\]:\s*http")


def convert(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        if LINKDEF.match(line):
            continue
        m = VERSION.match(line)
        if m:
            version, date = m.group(1), (m.group(2) or "").strip()
            if version.lower() == "unreleased":
                out.append(f"# {PACKAGE} (development version)")
            else:
                out.append(f"# {PACKAGE} {version}" + (f" ({date})" if date else ""))
            continue
        m = SECTION.match(line)
        if m:
            out.append(f"## {m.group(1)}")
            continue
        out.append(line)

    body = "\n".join(out)
    # The changelog's preamble explains the two-file arrangement, which is not
    # news. Everything before the first version heading goes.
    first = body.find(f"# {PACKAGE} ")
    if first > 0:
        body = body[first:]
    body = re.sub(r"\n{3,}", "\n\n", body).strip() + "\n"
    return BANNER + body


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if r/NEWS.md is out of date")
    args = ap.parse_args(argv)

    if not SOURCE.exists():
        print(f"{SOURCE.relative_to(ROOT)} not found")
        return 1

    text = convert(SOURCE.read_text(encoding="utf-8"))
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale; run docs/build_news.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)} "
          f"({text.count(chr(10)) + 1} lines) from {SOURCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
