#!/usr/bin/env python3
"""Emit ``docs/_quarto.yml`` and ``r/_pkgdown.yml`` from one grouping file.

Both reference trees are already generated -- quartodoc from the numpydoc
docstrings, pkgdown from the roxygen blocks -- so neither needs hand-writing.
The one thing that *did* need maintaining twice was the grouping: which
functions sit under which heading, which is what a reader navigates by. Two
YAML files edited separately drift within a release, and the drift is invisible
until somebody notices the Python site has a section the R site does not.

So the grouping lives in ``reference-groups.yml`` and both configs come from
here. Editing either output by hand is a mistake the next build reverts.

Usage
-----
    python docs/build_docs.py           # write both
    python docs/build_docs.py --check   # fail if either is stale (for CI)
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GROUPS = HERE / "reference-groups.yml"
QUARTO = HERE / "_quarto.yml"
PKGDOWN = ROOT / "r" / "_pkgdown.yml"

BANNER = ("# GENERATED by docs/build_docs.py from docs/reference-groups.yml.\n"
          "# Edit the grouping file, not this one -- the next build reverts it.\n")


def load():
    return yaml.safe_load(GROUPS.read_text(encoding="utf-8"))


def citation() -> dict:
    """Author, version and licence, read from CITATION.cff.

    The sidebar shows who wrote this and under what licence, and that
    information already exists in exactly one machine-readable place. Copying it
    into the site config would give two copies to keep in step across a release,
    and the one that goes stale would be the one rendered on every page.
    """
    cff = ROOT / "CITATION.cff"
    if not cff.exists():
        return {}
    doc = yaml.safe_load(cff.read_text(encoding="utf-8")) or {}
    author = (doc.get("authors") or [{}])[0]
    name = " ".join(x for x in (author.get("given-names"),
                                author.get("family-names")) if x)
    return {"author": name, "orcid": author.get("orcid", ""),
            "version": str(doc.get("version", "")),
            "license": doc.get("license", "")}


def apa(spec: dict) -> str:
    """The APA 7 reference for a software entry."""
    c = citation()
    surname = (c.get("author", "").split() or ["Hunakunti"])[-1]
    initials = "".join(f"{w[0]}." for w in c.get("author", "B").split()[:-1])
    return (f"{surname}, {initials} (2026). "
            f"FALCONAge: Multiomic biological age and aging clock scoring in "
            f"Python and R (Version {c.get('version', '')}) [Computer software]. "
            f"{spec['site']['repo']}")


def bibtex(spec: dict) -> str:
    c = citation()
    return "\n".join([
        "@software{falconage2026,",
        f"  author  = {{{c.get('author', '')}}},",
        "  title   = {FALCONAge: Multiomic Biological Age and Aging Clock "
        "Scoring in Python and R},",
        "  year    = {2026},",
        f"  version = {{{c.get('version', '')}}},",
        f"  url     = {{{spec['site']['repo']}}},",
        f"  license = {{{c.get('license', '')}}}",
        "}",
    ])


def _b64(text: str) -> str:
    """Base64 for a data- attribute.

    The citation used to live in hidden <pre> elements the copy handler read by
    id. Pandoc parses the sidebar `header:` as markdown, and a multi-line raw
    HTML block with a boolean `hidden` attribute made it stop parsing partway
    through -- the rendered page kept the title and silently dropped both <pre>
    tags AND the buttons after them. Nothing errored; the block was just short.
    That is why this is now one line with no hidden elements, no boolean
    attributes and no newlines inside a tag: there is nothing left for the
    markdown reader to trip on.
    """
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


def sidebar_header(spec: dict) -> str:
    """Logo, one line on what this is, and a citation you can paste.

    WHY THERE IS NO NAVIGATION HERE. The first version repeated the navbar down
    the left column, which is two copies of the same menu on a screen wide
    enough to show both and no help on one that is not. The right-hand "On this
    page" list already handles movement within a page. So the column carries
    what the navbar cannot: what the tool is, and how to cite it.

    WHY THE CITATION IS INLINE RATHER THAN A LINK. A link to CITATION.cff is a
    file to open, parse and reformat. What a reader wants is the two strings
    they are actually going to paste -- APA into a manuscript, BibTeX into a
    .bib -- with a button that puts them on the clipboard.
    """
    site = spec["site"]
    # No <img> here. An earlier version emitted one to control the order, and
    # `src="logo.png"` is relative to the page: correct at the site root and a
    # 404 on everything under guide/ and reference/, which is most of the site.
    # Quarto's own `logo:` key rewrites the path per page depth -- ./logo.png,
    # ../logo.png -- so the key does the job and CSS `order` puts the block
    # above this text. Ordering is a layout problem; it should be solved in the
    # stylesheet, not by hand-writing an image tag with a broken path.
    #
    # The citation text is in the DOM but hidden: the reader wants the button,
    # not two reference formats taking up a screen of a narrow column, and the
    # copy handler needs something to read.
    return (
        f'<p class="falcon-blurb">{" ".join(site["description"].split())}</p>\n'
        '<div class="falcon-cite">'
        '<div class="falcon-cite-title">Cite FALCONAge</div>'
        '<div class="falcon-cite-buttons">'
        f'<button class="falcon-copy" data-copy="{_b64(apa(spec))}">Copy APA</button>'
        f'<button class="falcon-copy" data-copy="{_b64(bibtex(spec))}">Copy BibTeX</button>'
        '</div>'
        '</div>'
    )


def quarto_yaml(spec: dict) -> str:
    site = spec["site"]
    cite = citation()
    sections = []
    for g in spec["groups"]:
        if not g.get("python"):
            continue
        sections.append({
            "title": g["title"],
            "desc": " ".join(g["desc"].split()),
            "contents": list(g["python"]),
        })

    doc = {
        # `resources` is a PROJECT key, not a website one. Quarto validates the
        # schema strictly and refuses the whole project when it is nested under
        # `website:`, which is where it is easy to assume it belongs given that
        # what it protects is the website's R subdirectory.
        #
        # What it does: pkgdown renders the R half into docs/r/ as finished
        # HTML. Without this Quarto either tries to render those files itself
        # or drops them from _site, and the "R reference" navbar link 404s.
        "project": {"type": "website", "output-dir": "_site",
                    "resources": ["r/**"]},
        "website": {
            "title": site["title"],
            "description": " ".join(site["description"].split()),
            "site-url": site["url"],
            "repo-url": site["repo"],
            "repo-actions": ["issue", "source"],
            "navbar": {
                # Ordered the way someone reads it: what the tool is, then the
                # science it rests on, then how to drive it, then the API.
                #
                # "About", not "Get started": guide/FALCONAge.qmd is called
                # "Getting started" and is the walkthrough. Two entries a menu
                # apart with near-identical names is a coin toss for the reader.
                "left": [
                    {"text": "About", "file": "index.qmd"},
                    {"text": "Background", "menu": [
                        {"text": p["title"], "file": p["file"]}
                        for p in spec.get("pages", [])]},
                    {"text": "Guides", "menu": [
                        {"text": a["title"], "file": f"guide/{a['file']}.qmd"}
                        for a in spec["articles"]]},
                    # One menu, two languages. They were top-level siblings, so
                    # the same idea occupied two slots and neither said it had a
                    # counterpart. `file` for the Python tree and `href` for R
                    # because pkgdown's output is copied in as a resource rather
                    # than rendered by Quarto.
                    {"text": "Reference", "menu": [
                        {"text": "Python reference", "file": "reference/index.qmd"},
                        {"text": "R reference", "href": "r/index.html"},
                    ]},
                ],
                "right": [
                    # href, not file: these are binaries copied into _site by
                    # build_downloads.py after the render, so Quarto must link
                    # to them rather than try to resolve them as pages.
                    {"text": "Download", "menu": [
                        {"text": d["title"], "href": f"downloads/{d['file']}"}
                        for d in spec.get("downloads", [])]},
                    {"icon": "github", "href": site["repo"]},
                ],
            },
            # WHY THE SIDEBAR CARRIES CONTENT AND NOT JUST A SEARCH BOX.
            # `style: docked` reserves a left column on every page. With no
            # `contents` Quarto puts the search box in it and leaves the rest
            # blank, which is a fifth of the viewport spent on nothing.
            #
            # So it holds what a reader wants persistently: the logo, one line
            # saying what the tool is, the whole site's navigation, and who
            # wrote it. `header` and `footer` take markdown, which is the only
            # place Quarto lets arbitrary prose into the sidebar.
            "sidebar": {
                "style": "docked",
                "search": True,
                # Quarto emits this into a block AFTER `header:`; the
                # stylesheet reorders it to the top. Using the key rather than
                # a hand-written <img> is what makes the path correct at every
                # page depth.
                "logo": "logo.png",
                "logo-alt": f"{site['title']} logo",
                "logo-href": site["url"],
                # Logo, then what it is, then how to cite it. No navigation:
                # the navbar already carries it, and repeating it down the left
                # is two copies of one menu. See sidebar_header().
                "header": sidebar_header(spec),
                # The licence links to the file rather than naming a string:
                # "GPL-3.0-or-later" is an identifier, and the thing a reader
                # actually wants is the terms.
                "footer": (
                    f"[{cite.get('author', '')}]({cite.get('orcid', '')})  \n"
                    f"[{cite.get('license', '')}]({site['repo']}/blob/main/LICENSE)"
                    f" · [source]({site['repo']})\n"
                ),
            },
        },
        "format": {"html": {
            # Declaring both a light and a dark theme is what makes Quarto put
            # the toggle in the navbar; there is no separate switch to turn on.
            #
            # BOTH sit on cosmo. The dark side was on `darkly`, and a Bootswatch
            # theme is not a colour scheme -- darkly sets Lato where cosmo sets
            # Source Sans Pro, with different metrics throughout, so toggling
            # changed every measurement on the page and the layout grew. One
            # base, one set of layout rules in _falcon-shared.scss which both
            # SCSS files import, and the dark file changes colour only.
            "theme": {"light": ["cosmo", "theme-light.scss"],
                      "dark": ["cosmo", "theme-dark.scss"]},
            "toc": True,
            "code-copy": True,
            "code-overflow": "wrap",
            # The copy buttons on the sidebar citation. Quarto's own code-copy
            # only decorates code blocks in the article body.
            "include-after-body": "cite-copy.html",
            # Both languages appear in the same tabset on every guide page, so
            # a reader picking "R" once keeps R selected across the whole site.
            "code-annotations": "hover",
        }},
        "quartodoc": {
            "package": "falconage",
            "dir": "reference",
            "title": "Python reference",
            "style": "pkgdown",
            # Off, and it has to be. Interlinks turn a type annotation into a
            # cross-reference by emitting `[](`pandas.DataFrame`)` for a Quarto
            # *filter* to resolve later. That filter ships as a Quarto
            # extension, installed separately with `quarto add machow/quartodoc`
            # -- and without it the placeholder reaches the HTML verbatim, so
            # every annotated parameter renders as a link whose href is a
            # backtick-quoted type name. Twenty-nine of those on the reference
            # pages, all 404.
            #
            # Adding the extension would mean vendoring a _extensions directory
            # and keeping it in step with quartodoc. Plain code formatting for
            # type names costs a reader nothing here: the types are numpy,
            # pandas and this package's own, and the ones that are ours have
            # their own page in the same reference.
            "render_interlinks": False,
            "sections": sections,
        },
    }
    return BANNER + yaml.safe_dump(doc, sort_keys=False, width=88,
                                   default_flow_style=False, allow_unicode=True)


def pkgdown_yaml(spec: dict) -> str:
    site = spec["site"]
    reference = []
    for g in spec["groups"]:
        if not g.get("r"):
            continue
        reference.append({
            "title": g["title"],
            "desc": " ".join(g["desc"].split()),
            "contents": list(g["r"]),
        })

    doc = {
        "url": site["url"] + "r/",
        # The same logo orange as the Quarto half, and pkgdown's own dark-mode
        # switch so the two sites behave alike when a reader crosses between
        # them. #a84800 is the darker shade: pkgdown uses `primary` for body
        # links, where the logo colour itself is only 3.4:1 on white.
        "template": {
            "bootstrap": 5,
            "light-switch": True,
            "bslib": {"primary": "#a84800", "link-color": "#a84800"},
        },
        "home": {"title": f"{site['title']} for R",
                 "description": " ".join(site["description"].split())},
        # The background pages are rendered once, by Quarto, and linked to from
        # here. Copying them into r/vignettes/ would duplicate five thousand
        # lines into the CRAN tarball, where a reference manual belongs and a
        # literature review does not -- and would give two copies to keep in
        # step, which is exactly the failure this whole file exists to prevent.
        "navbar": {
            "structure": {"left": ["intro", "reference", "articles", "background"],
                          "right": ["search", "github", "main"]},
            "components": {
                "main": {"text": "Full site", "href": site["url"]},
                "background": {
                    "text": "Background",
                    "menu": [{"text": p["title"],
                              "href": site["url"] + Path(p["file"]).with_suffix(".html").name}
                             for p in spec.get("pages", [])],
                },
            },
        },
        "reference": reference,
        "articles": [{
            "title": "Guides",
            "navbar": "~",
            "contents": [a["file"] for a in spec["articles"]],
        }],
    }
    return BANNER + yaml.safe_dump(doc, sort_keys=False, width=88,
                                   default_flow_style=False, allow_unicode=True)


def coverage_report(spec: dict) -> list[str]:
    """Flag groups that exist in one language and not the other.

    Not an error -- `download` is Python-only by design, because an R user gets
    it through the same core -- but worth printing, because a group that is
    empty on one side by accident looks identical to one that is empty on
    purpose.
    """
    out = []
    for g in spec["groups"]:
        py, r = len(g.get("python") or []), len(g.get("r") or [])
        if bool(py) != bool(r):
            out.append(f"  {g['title']}: {py} Python, {r} R")
    return out


R_README = ROOT / "r" / "README.md"
INDEX = HERE / "index.qmd"
MAP_BEGIN = "<!-- BEGIN GENERATED: api-map -->"
MAP_END = "<!-- END GENERATED: api-map -->"
CITE_BEGIN = "<!-- BEGIN GENERATED: citation -->"
CITE_END = "<!-- END GENERATED: citation -->"


def citation_block(spec: dict) -> str:
    """A copy-paste citation, in the two forms anyone actually needs.

    Written from CITATION.cff so the version and the author cannot disagree
    with the file GitHub's "Cite this repository" button reads. Both are fenced
    code blocks because Quarto puts a copy button on those, which is the whole
    point -- a citation you have to select by hand gets retyped wrong.
    """
    site = spec["site"]
    # The same two strings the sidebar buttons copy, from the same functions.
    # A page that shows one citation and a button that copies a different one
    # is worse than either alone.
    return "\n".join([
        CITE_BEGIN,
        "",
        "APA:",
        "",
        "```",
        apa(spec),
        "```",
        "",
        "BibTeX:",
        "",
        "```bibtex",
        bibtex(spec),
        "```",
        "",
        'In R, `citation("FALCONAge")`. The machine-readable version is',
        f"[CITATION.cff]({site['repo']}/blob/main/CITATION.cff), which is what",
        "GitHub's *Cite this repository* button reads.",
        "",
        "The clock FALCONAge computed for you is somebody else's work, and citing",
        "FALCONAge does not cite it. Every registry entry carries its primary",
        "reference, so the list for an analysis comes out of the analysis:",
        "",
        "::: {.panel-tabset}",
        "",
        "### Python",
        "",
        "```python",
        'fa.registry.load().get("grimage2").cite("bibtex")',
        "```",
        "",
        "### R",
        "",
        "```r",
        'cite_clock("grimage2", "bibtex")',
        "```",
        "",
        ":::",
        "",
        CITE_END,
    ])


def fill_block(path: Path, begin: str, end: str, body: str) -> str | None:
    """Replace a marked region in a hand-written file, or None if absent."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    if begin not in text or end not in text:
        return None
    head, _, rest = text.partition(begin)
    _, _, tail = rest.partition(end)
    return head + body + tail


def api_map(spec: dict) -> str:
    """The R-to-Python correspondence table, from the explicit `pairs` block.

    Paired entries first, then whatever each side has that the other does not.
    Positional pairing was tried and is wrong: the lists are ordered by subject
    and differ in length, so it produced rows claiming `report()` was
    `fa.plot.palette()`.
    """
    pairs = spec.get("pairs") or {}
    lines = [MAP_BEGIN, "", "| | R | Python |", "|---|---|---|"]
    for g in spec["groups"]:
        r, py = list(g.get("r") or []), list(g.get("python") or [])
        rows = [(a, b) for a, b in pairs.get(g["title"], [])]
        paired_r = {a for a, _ in rows}
        paired_py = {b for _, b in rows}
        rows += [(x, None) for x in r if x not in paired_r]
        rows += [(None, x) for x in py if x not in paired_py]
        if not rows:
            continue
        for i, (rn, pn) in enumerate(rows):
            group = f"**{g['title']}**" if i == 0 else ""
            lines.append(f"| {group} | {f'`{rn}()`' if rn else '—'} "
                         f"| {f'`fa.{pn}()`' if pn else '—'} |")
    lines += ["", MAP_END]
    return "\n".join(lines)


def bad_pairs(spec: dict) -> list[str]:
    """Names in `pairs` that do not appear in the group they are filed under.

    Without this the table silently keeps rendering a function that has been
    renamed or moved, which is the failure mode the whole generated-file
    arrangement exists to prevent.
    """
    out = []
    by_title = {g["title"]: g for g in spec["groups"]}
    for title, rows in (spec.get("pairs") or {}).items():
        g = by_title.get(title)
        if g is None:
            out.append(f"pairs has a group {title!r} that is not in groups")
            continue
        r, py = set(g.get("r") or []), set(g.get("python") or [])
        for a, b in rows:
            if a not in r:
                out.append(f"{title}: R {a!r} is not in that group's r: list")
            if b not in py:
                out.append(f"{title}: Python {b!r} is not in that group's python: list")
    return out


def r_readme(spec: dict) -> str | None:
    """The R README with its generated mapping block filled in."""
    return fill_block(R_README, MAP_BEGIN, MAP_END, api_map(spec))


def index_page(spec: dict) -> str | None:
    """The landing page with its generated citation block filled in."""
    return fill_block(INDEX, CITE_BEGIN, CITE_END, citation_block(spec))


def ungrouped_r_topics(spec: dict) -> list[str]:
    """Exported R topics that no group claims. This one IS an error.

    pkgdown refuses to build a site when a public topic is in no reference
    group, and it discovers this two minutes into the docs job with a message
    that names the topics but not the file to put them in. Catching it here
    turns a CI failure into a line of output from a script that runs in a
    second.

    The comparison is against ``r/man/*.Rd`` rather than NAMESPACE, because a
    topic is what pkgdown indexes: several S3 methods share one ``.Rd`` through
    ``@rdname`` and must not be listed separately, and anything carrying
    ``\\keyword{internal}`` is deliberately excluded from the index.
    """
    man = ROOT / "r" / "man"
    if not man.is_dir():
        return []
    public = {p.stem for p in man.glob("*.Rd")
              if "\\keyword{internal}" not in p.read_text(encoding="utf-8")}
    listed = {n for g in spec["groups"] for n in (g.get("r") or [])}
    return sorted(public - listed)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if either output is stale")
    args = ap.parse_args(argv)

    spec = load()
    outputs = {QUARTO: quarto_yaml(spec), PKGDOWN: pkgdown_yaml(spec)}
    for path, text in ((R_README, r_readme(spec)), (INDEX, index_page(spec))):
        if text is not None:
            outputs[path] = text

    stale = []
    for path, text in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(path)

    orphans = ungrouped_r_topics(spec)
    mispairs = bad_pairs(spec)
    if mispairs:
        print("the R-to-Python pairing names functions that are not in their group:")
        for m in mispairs:
            print(f"  {m}")
        return 1

    if args.check:
        bad = False
        if stale:
            print("stale, regenerate with docs/build_docs.py:")
            for p in stale:
                print(f"  {p.relative_to(ROOT)}")
            bad = True
        if orphans:
            print(f"{len(orphans)} exported R topic(s) belong to no reference group.")
            print("pkgdown will refuse to build the site until each is either")
            print("added to a group in docs/reference-groups.yml or marked")
            print("@keywords internal:")
            for t in orphans:
                print(f"  {t}")
            bad = True
        if bad:
            return 1
        print("both configs are current; every exported R topic is grouped")
        return 0

    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")

    if orphans:
        print(f"\nWARNING: {len(orphans)} exported R topic(s) in no group. "
              "pkgdown will refuse to build:")
        for t in orphans:
            print(f"  {t}")

    asym = coverage_report(spec)
    if asym:
        print("\ngroups present in one language only:")
        print("\n".join(asym))
    return 1 if orphans else 0


if __name__ == "__main__":
    sys.exit(main())
