#!/usr/bin/env python3
"""Generate ``docs/clocks.qmd`` -- the clock catalogue -- from the registry.

WHY THIS IS GENERATED RATHER THAN EXECUTED AT RENDER TIME. The page began as a
Quarto document with a live ``{python}`` chunk that queried the registry. That
works, and it costs a Jupyter installation on every machine that renders the
site -- nbformat, ipykernel, jupyter-client and their dependencies -- to run one
loop over 161 dataclasses. It also moves a failure that belongs at build time
into the middle of a 138-file render, where the message is
``ModuleNotFoundError: No module named 'nbformat'`` and the cause is four steps
away.

Generating it instead removes the dependency, makes the render deterministic and
offline, and puts this page in the same category as the other three generated
files: edit the source of truth, run the script, commit the output. CI fails if
the two have drifted.

The source of truth is the registry the package ships, so the page cannot
describe a catalogue different from the one that scores.

Usage
-----
    python docs/build_catalogue.py           # write docs/clocks.qmd
    python docs/build_catalogue.py --check   # fail if it is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TARGET = HERE / "clocks.qmd"

# The scale-type table on the About page. Same source of truth, different page,
# so it lives here rather than in build_docs.py, which never imports falconage.
#
# It is generated for the same reason the catalogue is: it was hand-written
# first, and it was wrong within the hour. `age_years` is not only years -- the
# registry has clocks reported in days and in months on that scale -- and a
# table that quietly disagrees with the code it documents is worse than no
# table, because a reader has no way to tell which one lied.
INDEX = HERE / "index.qmd"
SCALE_BEGIN = "<!-- BEGIN GENERATED: scales -->"
SCALE_END = "<!-- END GENERATED: scales -->"

# What the scale means in words. Not derivable from the registry -- it is the
# one column a human has to write -- so a new scale_type with no entry here is
# a hard failure rather than a blank cell.
GLOSS = {
    "age_years": "An age. The model predicts elapsed time and is reported on "
                 "the same scale as chronological age.",
    "relative_score": "A score with no external unit. Comparable within a "
                      "cohort, meaningless as an absolute value.",
    "proportion": "A composition. The estimates are fractions of a whole and "
                  "are constrained to sum to one.",
    "divisions": "A count of cell divisions, not elapsed time.",
    "gestational_weeks": "An age, before birth.",
    "telomere_kb": "An estimated physical length.",
    "pace_ratio": "A rate: how much biological ageing per year of calendar "
                  "time, at the moment of sampling.",
    "mortality_log_hazard": "A risk on the log-hazard scale. Exponentiating a "
                            "difference gives a hazard ratio.",
}

BANNER = ("<!-- GENERATED by docs/build_catalogue.py from the shipped registry.\n"
          "     Edit that script or the registry, not this file. -->")

TIER = {
    "A": "Coefficients ship with the package, or the clock is a formula with "
         "none to ship. Works offline, no network, no licence.",
    "B": "Catalogued, but no primary source for the coefficients has been "
         "established, so nothing is bundled. The metadata is real; the "
         "numbers are absent.",
    "C": "The architecture is implemented and tested; the coefficients are "
         "research-use-only and are not ours to distribute. Obtain a file and "
         "register it.",
}

HEAD = """---
title: "Clock catalogue"
subtitle: "All {n}, generated from the registry that scores them"
---

{banner}

This page is written from the registry the package ships, so it cannot describe
a catalogue different from the one that scores. Every column below is a field
the scoring code reads.

`scale_type` is the load-bearing one. It is not a label -- it decides which
downstream operations FALCONAge will perform, and asking for age acceleration
on a `pace_ratio` clock is refused rather than computed.

**{n} clocks**, registry schema `{schema}`.
"""

TAIL = """
## Querying it from code

::: {.panel-tabset}

### Python

```python
reg = fa.registry.load()
reg.filter(availability="A", scale_type="age_years")
reg.search("mortality")
reg.compatible_with(data)
reg.get("horvath2013")
```

### R

```r
list_clocks(tier = "A")
list_clocks(search = "mortality")
compatible_clocks(d)
clock_info("horvath2013")
```

:::
"""


def render() -> str:
    import falconage as fa

    reg = fa.registry.load()
    clocks = sorted(reg, key=lambda c: (c.availability, c.id))

    out = [HEAD.format(n=len(clocks), schema=reg.version, banner=BANNER)]
    for tier in ("A", "B", "C"):
        rows = [c for c in clocks if c.availability == tier]
        out.append(f"\n## Tier {tier} — {len(rows)} clocks\n")
        out.append(TIER[tier] + "\n")
        out.append("| Clock | Year | Predicts | Scale | Features | Platform |")
        out.append("|---|---:|---|---|---:|---|")
        for c in rows:
            plat = ", ".join(c.platform) or "—"
            out.append(f"| `{c.id}` | {c.year or '—'} | {c.name} | "
                       f"`{c.scale_type}` | {c.n_features or '—'} | {plat} |")
        out.append("")
    out.append(TAIL)
    return "\n".join(out)


def scale_table() -> str:
    """The About page's scale-type table, read off the registry and LEGAL_OPS."""
    import falconage as fa

    reg = fa.registry.load()
    rows = {}
    for c in reg:
        s = rows.setdefault(c.scale_type, {"n": 0, "units": Counter()})
        s["n"] += 1
        s["units"].update(c.unit)

    missing = sorted(set(rows) - set(GLOSS))
    if missing:
        raise SystemExit(
            "docs/build_catalogue.py: no gloss for scale_type "
            + ", ".join(missing) + " -- add one to GLOSS.")

    out = [SCALE_BEGIN, "",
           "| `scale_type` | n | What the number is | Units in the registry "
           "| Operations permitted |",
           "|---|---:|---|---|---|"]
    for s, v in sorted(rows.items(), key=lambda kv: -kv[1]["n"]):
        ops = ", ".join(sorted(fa.registry.LEGAL_OPS[s])).replace("_", " ")
        # Commonest first, capped. `relative_score` spans fifteen different
        # unit strings -- which is the point of the scale, not a defect -- and
        # printing all of them makes the row unreadable and the column useless.
        top = [u for u, _ in v["units"].most_common(3)]
        rest = len(v["units"]) - len(top)
        units = ", ".join(top) + (f", and {rest} more" if rest else "")
        out.append(f"| `{s}` | {v['n']} | {GLOSS[s]} | {units} | {ops} |")
    out += ["", SCALE_END]
    return "\n".join(out)


def render_index() -> str:
    """docs/index.qmd with the scale block replaced."""
    text = INDEX.read_text(encoding="utf-8")
    start, end = text.find(SCALE_BEGIN), text.find(SCALE_END)
    if start == -1 or end == -1:
        raise SystemExit(f"docs/index.qmd has no {SCALE_BEGIN} block")
    return text[:start] + scale_table() + text[end + len(SCALE_END):]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if either generated file is out of date")
    args = ap.parse_args(argv)

    try:
        text = render()
        index = render_index()
    except ImportError:
        print("falconage is not importable; install it before generating the "
              "catalogue (pip install ./python)")
        return 1

    pairs = [(TARGET, text), (INDEX, index)]
    if args.check:
        stale = [p for p, want in pairs
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != want]
        if stale:
            print(", ".join(str(p.relative_to(ROOT)) for p in stale)
                  + " is stale; run docs/build_catalogue.py")
            return 1
        print("docs/clocks.qmd and docs/index.qmd are current")
        return 0

    for p, want in pairs:
        p.write_text(want, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
