#!/usr/bin/env python3
"""Emit ``docs/_quarto.yml`` and ``r/_pkgdown.yml`` from one grouping file.

Both reference trees are already generated -- quartodoc from the numpydoc
docstrings, pkgdown from the roxygen blocks -- so neither needs hand-writing.
The one thing that *did* need maintaining twice was the grouping: which
functions sit under which heading, which is what a reader navigates by. Two
YAML files edited separately drift within a release, and the drift is invisible
until somebody notices the Python site has a section the R site does not.

So the grouping lives in ``reference-groups.yml`` and both configs come from
here. Editing either output by hand is a mistake the next build reverts.

Usage
-----
    python docs/build_docs.py           # write both
    python docs/build_docs.py --check   # fail if either is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GROUPS = HERE / "reference-groups.yml"
QUARTO = HERE / "_quarto.yml"
PKGDOWN = ROOT / "r" / "_pkgdown.yml"

BANNER = ("# GENERATED by docs/build_docs.py from docs/reference-groups.yml.\n"
          "# Edit the grouping file, not this one -- the next build reverts it.\n")


def load():
    return yaml.safe_load(GROUPS.read_text(encoding="utf-8"))


def quarto_yaml(spec: dict) -> str:
    site = spec["site"]
    sections = []
    for g in spec["groups"]:
        if not g.get("python"):
            continue
        sections.append({
            "title": g["title"],
            "desc": " ".join(g["desc"].split()),
            "contents": list(g["python"]),
        })

    doc = {
        "project": {"type": "website", "output-dir": "_site"},
        "website": {
            "title": site["title"],
            "description": " ".join(site["description"].split()),
            "site-url": site["url"],
            "repo-url": site["repo"],
            "repo-actions": ["issue", "source"],
            "navbar": {
                "left": [
                    {"text": "Get started", "file": "index.qmd"},
                    {"text": "Guides", "menu": [
                        {"text": a["title"], "file": f"guide/{a['file']}.qmd"}
                        for a in spec["articles"]]},
                    {"text": "Python reference", "file": "reference/index.qmd"},
                    {"text": "R reference", "href": "r/index.html"},
                    {"text": "Background", "menu": [
                        {"text": p["title"], "file": p["file"]}
                        for p in spec.get("pages", [])]},
                ],
                "right": [
                    # href, not file: these are binaries copied into _site by
                    # build_downloads.py after the render, so Quarto must link
                    # to them rather than try to resolve them as pages.
                    {"text": "Download", "menu": [
                        {"text": d["title"], "href": f"downloads/{d['file']}"}
                        for d in spec.get("downloads", [])]},
                    {"icon": "github", "href": site["repo"]},
                ],
            },
            "sidebar": {"style": "docked", "search": True},
            # The R site is rendered by pkgdown into docs/r/ and served as
            # static assets. Quarto must not try to render it.
            "resources": ["r/**"],
        },
        "format": {"html": {
            "theme": ["cosmo"],
            "toc": True,
            "code-copy": True,
            "code-overflow": "wrap",
            # Both languages appear in the same tabset on every guide page, so
            # a reader picking "R" once keeps R selected across the whole site.
            "code-annotations": "hover",
        }},
        "quartodoc": {
            "package": "falconage",
            "dir": "reference",
            "title": "Python reference",
            "style": "pkgdown",
            "render_interlinks": True,
            "sections": sections,
        },
    }
    return BANNER + yaml.safe_dump(doc, sort_keys=False, width=88,
                                   default_flow_style=False, allow_unicode=True)


def pkgdown_yaml(spec: dict) -> str:
    site = spec["site"]
    reference = []
    for g in spec["groups"]:
        if not g.get("r"):
            continue
        reference.append({
            "title": g["title"],
            "desc": " ".join(g["desc"].split()),
            "contents": list(g["r"]),
        })

    doc = {
        "url": site["url"] + "r/",
        "template": {"bootstrap": 5, "bslib": {"primary": "#0072B2"}},
        "home": {"title": f"{site['title']} for R",
                 "description": " ".join(site["description"].split())},
        # The background pages are rendered once, by Quarto, and linked to from
        # here. Copying them into r/vignettes/ would duplicate five thousand
        # lines into the CRAN tarball, where a reference manual belongs and a
        # literature review does not -- and would give two copies to keep in
        # step, which is exactly the failure this whole file exists to prevent.
        "navbar": {
            "structure": {"left": ["intro", "reference", "articles", "background"],
                          "right": ["search", "github", "main"]},
            "components": {
                "main": {"text": "Full site", "href": site["url"]},
                "background": {
                    "text": "Background",
                    "menu": [{"text": p["title"],
                              "href": site["url"] + Path(p["file"]).with_suffix(".html").name}
                             for p in spec.get("pages", [])],
                },
            },
        },
        "reference": reference,
        "articles": [{
            "title": "Guides",
            "navbar": "~",
            "contents": [a["file"] for a in spec["articles"]],
        }],
    }
    return BANNER + yaml.safe_dump(doc, sort_keys=False, width=88,
                                   default_flow_style=False, allow_unicode=True)


def coverage_report(spec: dict) -> list[str]:
    """Flag groups that exist in one language and not the other.

    Not an error -- `download` is Python-only by design, because an R user gets
    it through the same core -- but worth printing, because a group that is
    empty on one side by accident looks identical to one that is empty on
    purpose.
    """
    out = []
    for g in spec["groups"]:
        py, r = len(g.get("python") or []), len(g.get("r") or [])
        if bool(py) != bool(r):
            out.append(f"  {g['title']}: {py} Python, {r} R")
    return out


def ungrouped_r_topics(spec: dict) -> list[str]:
    """Exported R topics that no group claims. This one IS an error.

    pkgdown refuses to build a site when a public topic is in no reference
    group, and it discovers this two minutes into the docs job with a message
    that names the topics but not the file to put them in. Catching it here
    turns a CI failure into a line of output from a script that runs in a
    second.

    The comparison is against ``r/man/*.Rd`` rather than NAMESPACE, because a
    topic is what pkgdown indexes: several S3 methods share one ``.Rd`` through
    ``@rdname`` and must not be listed separately, and anything carrying
    ``\\keyword{internal}`` is deliberately excluded from the index.
    """
    man = ROOT / "r" / "man"
    if not man.is_dir():
        return []
    public = {p.stem for p in man.glob("*.Rd")
              if "\\keyword{internal}" not in p.read_text(encoding="utf-8")}
    listed = {n for g in spec["groups"] for n in (g.get("r") or [])}
    return sorted(public - listed)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if either output is stale")
    args = ap.parse_args(argv)

    spec = load()
    outputs = {QUARTO: quarto_yaml(spec), PKGDOWN: pkgdown_yaml(spec)}

    stale = []
    for path, text in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(path)

    orphans = ungrouped_r_topics(spec)

    if args.check:
        bad = False
        if stale:
            print("stale, regenerate with docs/build_docs.py:")
            for p in stale:
                print(f"  {p.relative_to(ROOT)}")
            bad = True
        if orphans:
            print(f"{len(orphans)} exported R topic(s) belong to no reference group.")
            print("pkgdown will refuse to build the site until each is either")
            print("added to a group in docs/reference-groups.yml or marked")
            print("@keywords internal:")
            for t in orphans:
                print(f"  {t}")
            bad = True
        if bad:
            return 1
        print("both configs are current; every exported R topic is grouped")
        return 0

    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")

    if orphans:
        print(f"\nWARNING: {len(orphans)} exported R topic(s) in no group. "
              "pkgdown will refuse to build:")
        for t in orphans:
            print(f"  {t}")

    asym = coverage_report(spec)
    if asym:
        print("\ngroups present in one language only:")
        print("\n".join(asym))
    return 1 if orphans else 0


if __name__ == "__main__":
    sys.exit(main())
