#!/usr/bin/env python3
"""Generate ``docs/clocks.qmd`` -- the clock catalogue -- from the registry.

WHY THIS IS GENERATED RATHER THAN EXECUTED AT RENDER TIME. The page began as a
Quarto document with a live ``{python}`` chunk that queried the registry. That
works, and it costs a Jupyter installation on every machine that renders the
site -- nbformat, ipykernel, jupyter-client and their dependencies -- to run one
loop over 161 dataclasses. It also moves a failure that belongs at build time
into the middle of a 138-file render, where the message is
``ModuleNotFoundError: No module named 'nbformat'`` and the cause is four steps
away.

Generating it instead removes the dependency, makes the render deterministic and
offline, and puts this page in the same category as the other three generated
files: edit the source of truth, run the script, commit the output. CI fails if
the two have drifted.

The source of truth is the registry the package ships, so the page cannot
describe a catalogue different from the one that scores.

Usage
-----
    python docs/build_catalogue.py           # write docs/clocks.qmd
    python docs/build_catalogue.py --check   # fail if it is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TARGET = HERE / "clocks.qmd"

# The scale-type table on the About page. Same source of truth, different page,
# so it lives here rather than in build_docs.py, which never imports falconage.
#
# It is generated for the same reason the catalogue is: it was hand-written
# first, and it was wrong within the hour. `age_years` is not only years -- the
# registry has clocks reported in days and in months on that scale -- and a
# table that quietly disagrees with the code it documents is worse than no
# table, because a reader has no way to tell which one lied.
INDEX = HERE / "index.qmd"
SCALE_BEGIN = "<!-- BEGIN GENERATED: scales -->"
SCALE_END = "<!-- END GENERATED: scales -->"

# What the scale means in words. Not derivable from the registry -- it is the
# one column a human has to write -- so a new scale_type with no entry here is
# a hard failure rather than a blank cell.
GLOSS = {
    "age_years": "An age. The model predicts elapsed time and is reported on "
                 "the same scale as chronological age.",
    "age_years_relative": "An age in years with a slope near one against "
                          "chronological age, but no fixed origin: the offset "
                          "moves between cohorts. The residual and group "
                          "differences are defined; predicted minus "
                          "chronological is not.",
    "relative_score": "A score with no external unit. Comparable within a "
                      "cohort, meaningless as an absolute value.",
    "proportion": "A composition. The estimates are fractions of a whole and "
                  "are constrained to sum to one.",
    "divisions": "A count of cell divisions, not elapsed time.",
    "gestational_weeks": "An age, before birth.",
    "telomere_kb": "An estimated physical length.",
    "pace_ratio": "A rate: how much biological ageing per year of calendar "
                  "time, at the moment of sampling.",
    "mortality_log_hazard": "A risk on the log-hazard scale. Exponentiating a "
                            "difference gives a hazard ratio.",
}

BANNER = ("<!-- GENERATED by docs/build_catalogue.py from the shipped registry.\n"
          "     Edit that script or the registry, not this file. -->")

TIER = {
    "bundled": "Coefficients ship with the package, or the clock is a formula with "
         "none to ship. Works offline, no network, no licence.",
    "untraced": "Catalogued, but no primary source for the coefficients has been "
         "established, so nothing is bundled. The metadata is real; the "
         "numbers are absent.",
    "licensed": "The architecture is implemented and tested; the coefficients are "
         "research-use-only and are not ours to distribute. Obtain a file and "
         "register it.",
}

HEAD = """---
title: "Clock catalogue"
subtitle: "All {n}, generated from the registry that scores them"
---

{banner}

This page is written from the registry the package ships, so it cannot describe
a catalogue different from the one that scores. Every column below is a field
the scoring code reads.

`scale_type` is the load-bearing one. It is not a label: it decides which
downstream operations FALCONAge will perform, and asking for age acceleration
on a `pace_ratio` clock is refused rather than computed.

**{n} clocks**, registry schema `{schema}`.

![What separates the three availability groups, and what a traced coefficient source means](images/tiers-and-provenance.png)

Availability is about provenance, not about quality. A `bundled` clock has a
coefficient file whose origin was followed back to the paper or its supplement
and checksummed, so the same numbers come out on any machine with no network.
An `untraced` clock has no public source for its coefficients, and a `licensed`
one has a source whose terms do not permit redistribution. Copying a coefficient
vector out of another package would move clocks into the bundled column and is
the one route not taken here, because a number with no source behind it cannot
be checked against anything.
"""

TAIL = """
## Querying it from code

::: {.panel-tabset}

### Python

```python
reg = fa.registry.load()
reg.filter(availability="bundled", scale_type="age_years")
reg.search("mortality")
reg.compatible_with(data)
reg.get("horvath2013")
```

### R

```r
list_clocks(tier = "bundled")
list_clocks(search = "mortality")
compatible_clocks(d)
clock_info("horvath2013")
```

:::
"""


def _predicts(c) -> str:
    """What the clock estimates, in words a reader has not already read.

    ``name`` is often just the identifier again -- "dnamphenoage predicts
    dnamphenoage" -- which fills a column and says nothing. Prefer the
    ``predicts`` field, fall back to the training target, and only then to the
    name. All three are registry fields; this picks the first that is not a
    restatement of the row's first cell.
    """
    cid = str(c.id).lower().replace("_", "").replace("-", "")

    def informative(vals) -> str | None:
        for v in vals:
            s = str(v).strip()
            if s and s.lower().replace(" ", "").replace("_", "") != cid:
                return s
        return None

    return (informative(c.predicts) or informative([c.name])
            or informative(c.training_target) or "—")


def _paper(c) -> str:
    """A link to the source, or a plain citation when there is no DOI.

    The whole point of the catalogue is that a reader can go and check; a table
    of 161 clock names with nothing to follow is a list, not a reference. DOIs
    are rendered as links because that is the durable identifier -- a journal
    URL rots and a DOI does not.
    """
    label = _short_cite(c)
    doi = (c.doi or "").strip()
    if doi:
        url = doi if doi.startswith("http") else f"https://doi.org/{doi}"
        return f"[{label}]({url})"
    return label


def _short_cite(c) -> str:
    """"Horvath 2013" from a full citation string, in whatever style it is in.

    The registry's citations arrive in at least three house styles -- APA,
    a quoted-title form, and an npj-ish one -- so the surname is taken as the
    text before the first comma or period, whichever comes first, and the year
    from the entry's own ``year`` field rather than parsed out of the string.
    Splitting on the first period alone gave "Levine, M", which is a surname
    and a dangling initial.
    """
    import re

    cite = (c.citation or "").strip()
    if not cite:
        return str(c.year or "—")
    first = re.split(r"[,.]", cite, maxsplit=1)[0].strip()
    # "de Lima Camillo" and "Bahado-Singh" are surnames; a lone initial is not.
    if not first or len(first) < 2:
        first = cite[:20].strip()
    return f"{first} {c.year}" if c.year else first


def render() -> str:
    import falconage as fa

    reg = fa.registry.load()
    clocks = sorted(reg, key=lambda c: (c.availability, c.id))

    out = [HEAD.format(n=len(clocks), schema=reg.version, banner=BANNER)]
    for tier in ("bundled", "untraced", "licensed"):
        rows = [c for c in clocks if c.availability == tier]
        out.append(f"\n## {tier.capitalize()}: {len(rows)} clocks\n")
        out.append(TIER[tier] + "\n")
        out.append("| Clock | Year | Predicts | Scale | Features | Tissue | Platform | Paper |")
        out.append("|---|---:|---|---|---:|---|---|---|")
        for c in rows:
            out.append("| " + " | ".join([
                f"`{c.id}`", str(c.year or "—"), _predicts(c), f"`{c.scale_type}`",
                str(c.n_features or "—"), ", ".join(c.tissue) or "—",
                ", ".join(c.platform) or "—", _paper(c),
            ]) + " |")
        out.append("")
    out.append(TAIL)
    return "\n".join(out)


def scale_table() -> str:
    """The About page's scale-type table, read off the registry and LEGAL_OPS."""
    import falconage as fa

    reg = fa.registry.load()
    rows = {}
    for c in reg:
        s = rows.setdefault(c.scale_type, {"n": 0, "units": Counter()})
        s["n"] += 1
        s["units"].update(c.unit)

    missing = sorted(set(rows) - set(GLOSS))
    if missing:
        raise SystemExit(
            "docs/build_catalogue.py: no gloss for scale_type "
            + ", ".join(missing) + " -- add one to GLOSS.")

    out = [SCALE_BEGIN, "",
           "| `scale_type` | n | What the number is | Units in the registry "
           "| Operations permitted |",
           "|---|---:|---|---|---|"]
    for s, v in sorted(rows.items(), key=lambda kv: -kv[1]["n"]):
        ops = ", ".join(sorted(fa.registry.LEGAL_OPS[s])).replace("_", " ")
        # Commonest first, capped. `relative_score` spans fifteen different
        # unit strings -- which is the point of the scale, not a defect -- and
        # printing all of them makes the row unreadable and the column useless.
        top = [u for u, _ in v["units"].most_common(3)]
        rest = len(v["units"]) - len(top)
        units = ", ".join(top) + (f", and {rest} more" if rest else "")
        out.append(f"| `{s}` | {v['n']} | {GLOSS[s]} | {units} | {ops} |")
    out += ["", SCALE_END]
    return "\n".join(out)



GUIDE = HERE / "guide" / "clocks.qmd"
QUESTION_BEGIN = "<!-- BEGIN GENERATED: by-question -->"
QUESTION_END = "<!-- END GENERATED: by-question -->"
TIERS_BEGIN = "<!-- BEGIN GENERATED: tiers -->"
TIERS_END = "<!-- END GENERATED: tiers -->"

#: The question a reader arrives with, and a pattern over the `predicts` field
#: that answers it. **Ordered: first match wins**, so the specific rules come
#: before the general ones -- "physical-fitness biological age" has to be caught
#: by the organ-system rule before the plain "biological age" one takes it.
#:
#: Patterns rather than exact strings. The registry holds 83 distinct `predicts`
#: values across 161 clocks, of which the hand-written version of this table
#: named nine; matching literally would mean editing this list every time a
#: clock is catalogued, and the page would drift again the first time somebody
#: forgot. A value that matches nothing is reported by
#: :func:`unrouted_predicts` and fails the build rather than vanishing from the
#: page that exists to help people find clocks.
QUESTIONS: list[tuple[str, str]] = [
    ("How old does this sample look?",
     r"^(chronological|relative) age$|retroelement methylation age"),
    ("How old is this newborn, gestationally?",
     r"gestational age"),
    ("How fast is this person aging?",
     r"pace of aging|intervention-responsive"),
    ("Which organ system is aging fastest?",
     r"[- ]system biological age|multisystem|physical-fitness biological age"),
    ("Who is at risk of dying sooner, or is frailer?",
     r"mortality|phenotypic age|^biological age$|frailty|healthspan|lifespan"
     r"|frailty index|electronic medical record age"
     r"|physiological dysregulation|intrinsic capacity|time to death"),
    ("Is damage separable from adaptation?",
     r"(damaging|adaptive|causal) epigenetic age"),
    ("How much has this tissue divided?",
     r"mitotic|replicative|divisions|proliferation|passage age|senescence"),
    ("What is the blood's cell composition?",
     r"proportion|cell composition"),
    ("How long are the telomeres?",
     r"telomere"),
    ("What is this person exposed to, or how do they live?",
     r"smoking|alcohol|body mass|BMI|body fat|cholesterol|waist|hip|VO2max"
     r"|grip strength|gait speed|educational attainment|stress|physical activity"
     r"|diet|exposure"),
    ("What is a specific protein or lab value likely to be?",
     r"C-reactive protein|GDF-15|PAI-1|TIMP-1|adrenomedullin|beta-2-microglobulin"
     r"|beta-2 microglobulin|cystatin C|interleukin|leptin|hemoglobin A1c"
     r"|growth differentiation factor|plasminogen activator|TIMP metallopeptidase"
     r"|smoking pack-years|methylation$|methylation score"),
    ("Is a named disease more likely?",
     r"disease|cancer|carcinoma|Alzheimer|depressive|syndrome"),
    ("What is the sample's chromosomal sex, or its species?",
     r"chromosome|^sex$|species"),
]


def _bucket(pred: tuple[str, ...]) -> str | None:
    import re

    for p in pred:
        s = str(p).strip()
        for question, pattern in QUESTIONS:
            if re.search(pattern, s, flags=re.IGNORECASE):
                return question
    return None


def unrouted_predicts() -> dict[str, list[str]]:
    """`predicts` values that no question above claims, and who has them.

    Reported rather than swallowed. A clock nobody can find on the page that
    exists to help people find clocks is worse than an ugly extra row.
    """
    import falconage as fa

    out: dict[str, list[str]] = {}
    for c in fa.registry.load():
        if _bucket(c.predicts) is None:
            key = ", ".join(c.predicts) or "(nothing declared)"
            out.setdefault(key, []).append(c.id)
    return out


def question_table() -> str:
    """Every clock in the registry, routed to the question it answers.

    Generated because the hand-written version listed twenty-three of one
    hundred and sixty-one and had not been touched since v1.0. A reader
    choosing a clock needs the whole catalogue or none of it.
    """
    import falconage as fa

    reg = fa.registry.load()
    buckets: dict[str, list] = {q: [] for q, _ in QUESTIONS}
    for c in sorted(reg, key=lambda c: (c.availability, c.id)):
        q = _bucket(c.predicts)
        if q is not None:
            buckets[q].append(c)

    # Relative dash counts set the column widths. Pandoc reads them for pipe
    # tables, and without the hint the one-character tier column is given the
    # same share as the clock list beside it.
    out = [QUESTION_BEGIN, "",
           "| Question | Ready to score | Needs a coefficient file | Scale |",
           "|:-----------------|:----------------------------|:-------------|:------|"]
    for q, _ in QUESTIONS:
        cs = buckets[q]
        if not cs:
            continue
        ready = [c for c in cs if c.availability == "A"]
        other = [c for c in cs if c.availability != "A"]
        scales = sorted({c.scale_type for c in cs})

        def names(items, limit=8):
            shown = ", ".join(f"`{c.id}`" for c in items[:limit])
            more = len(items) - limit
            return (shown + (f", and {more} more" if more > 0 else "")) or "—"

        out.append(f"| {q} | {names(ready)} | {names(other)} | "
                   + ", ".join(f"`{s}`" for s in scales) + " |")
    out += ["",
            f"Every one of the {len(list(reg))} catalogued clocks appears above, routed by "
            "its declared `predicts` field. The full table with paper links is the "
            "[clock catalogue](../clocks.qmd).",
            "", QUESTION_END]
    return "\n".join(out)


def tier_table() -> str:
    """Availability counts, from the registry rather than from memory."""
    import falconage as fa

    reg = fa.registry.load()
    order = ("bundled", "untraced", "licensed")
    n = {t: sum(1 for c in reg if c.availability == t) for t in order}
    what = {
        "bundled": "Nothing. Coefficients ship inside the package, or the clock "
                   "is a formula with none.",
        "untraced": "Catalogued, but no primary source has been established, so "
                    "no coefficients ship.",
        "licensed": "Obtain a coefficient file and register it. The architecture "
                    "is implemented and tested.",
    }
    # Ten dashes for the first column against sixty for the last: Pandoc sizes
    # pipe-table columns from the separator row, and with an even split the
    # one-word column took a third of the width.
    out = [TIERS_BEGIN, "",
           "| Availability | n | What you do |",
           "|:---------|--:|:-------------------------------------------------------|"]
    for t in order:
        out.append(f"| `{t}` | {n[t]} | {what[t]} |")
    out += ["", TIERS_END]
    return "\n".join(out)


GSCALE_BEGIN = "<!-- BEGIN GENERATED: guide-scales -->"
GSCALE_END = "<!-- END GENERATED: guide-scales -->"

#: Why an operation is refused on a scale, in one clause. The permitted set is
#: read from LEGAL_OPS; this is the half a machine cannot write.
WHY_NOT = {
    "age_years": "—",
    "age_years_relative": "acceleration: the clock tracks age with a slope near "
                          "one but its origin moves between cohorts, so "
                          "predicted minus chronological measures the cohort",
    "gestational_weeks": "mixing with an age in years",
    "mortality_log_hazard": "acceleration: a log-hazard has no zero on the age scale",
    "pace_ratio": "acceleration: it is already a rate",
    "telomere_kb": "comparison with an age in years; and higher is the *younger* "
                   "direction here, unlike every age clock beside it",
    "proportion": "anything ignoring the sum-to-one constraint",
    "divisions": "acceleration: a division count is not elapsed time",
    "relative_score": "everything except correlation and rank: there is no "
                      "external unit to difference or average",
}


def guide_scale_table() -> str:
    """Scale, what it permits, and what it refuses -- from LEGAL_OPS itself.

    Hand-written at first, and by then it was missing three of the nine
    scales the registry uses, including the one added in the same release. A
    table of rules that omits a third of the rules is worse than no table.
    """
    import falconage as fa

    reg = fa.registry.load()
    n = Counter(c.scale_type for c in reg)
    missing = sorted(set(n) - set(WHY_NOT))
    if missing:
        raise SystemExit(
            "docs/build_catalogue.py: no WHY_NOT entry for scale_type "
            + ", ".join(missing))

    out = [GSCALE_BEGIN, "",
           "| Scale | Clocks | Permitted | Refused, and why |",
           "|:------------|---:|:------------------|:---------------------------|"]
    for s, count in sorted(n.items(), key=lambda kv: -kv[1]):
        ops = ", ".join(sorted(fa.registry.LEGAL_OPS[s])).replace("_", " ")
        out.append(f"| `{s}` | {count} | {ops} | {WHY_NOT[s]} |")
    out += ["", GSCALE_END]
    return "\n".join(out)


def render_guide() -> str:
    """guide/clocks.qmd with every generated block replaced."""
    text = GUIDE.read_text(encoding="utf-8")
    for begin, end, body in ((QUESTION_BEGIN, QUESTION_END, question_table()),
                             (GSCALE_BEGIN, GSCALE_END, guide_scale_table()),
                             (TIERS_BEGIN, TIERS_END, tier_table())):
        start, stop = text.find(begin), text.find(end)
        if start == -1 or stop == -1:
            raise SystemExit(f"docs/guide/clocks.qmd has no {begin} block")
        text = text[:start] + body + text[stop + len(end):]
    return text


def render_index() -> str:
    """docs/index.qmd with the scale block replaced."""
    text = INDEX.read_text(encoding="utf-8")
    start, end = text.find(SCALE_BEGIN), text.find(SCALE_END)
    if start == -1 or end == -1:
        raise SystemExit(f"docs/index.qmd has no {SCALE_BEGIN} block")
    return text[:start] + scale_table() + text[end + len(SCALE_END):]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if either generated file is out of date")
    args = ap.parse_args(argv)

    try:
        text = render()
        index = render_index()
        guide = render_guide()
    except ImportError:
        print("falconage is not importable; install it before generating the "
              "catalogue (pip install ./python)")
        return 1

    # A clock whose `predicts` value matches no question is invisible on the
    # page that exists to help people find clocks. Reported, not swallowed.
    stray = unrouted_predicts()
    if stray:
        print("predicts values not routed to any question on guide/clocks.qmd:")
        for k, ids in sorted(stray.items()):
            print(f"  {k!r}: {len(ids)} clock(s), e.g. {ids[:3]}")
        print("  add them to QUESTIONS in docs/build_catalogue.py")
        return 1

    pairs = [(TARGET, text), (INDEX, index), (GUIDE, guide)]
    if args.check:
        stale = [p for p, want in pairs
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != want]
        if stale:
            print(", ".join(str(p.relative_to(ROOT)) for p in stale)
                  + " is stale; run docs/build_catalogue.py")
            return 1
        print("docs/clocks.qmd, docs/index.qmd and docs/guide/clocks.qmd are current")
        return 0

    for p, want in pairs:
        p.write_text(want, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
