#!/usr/bin/env python3
"""Generate ``docs/clocks.qmd`` -- the clock catalogue -- from the registry.

WHY THIS IS GENERATED RATHER THAN EXECUTED AT RENDER TIME. The page began as a
Quarto document with a live ``{python}`` chunk that queried the registry. That
works, and it costs a Jupyter installation on every machine that renders the
site -- nbformat, ipykernel, jupyter-client and their dependencies -- to run one
loop over 161 dataclasses. It also moves a failure that belongs at build time
into the middle of a 138-file render, where the message is
``ModuleNotFoundError: No module named 'nbformat'`` and the cause is four steps
away.

Generating it instead removes the dependency, makes the render deterministic and
offline, and puts this page in the same category as the other three generated
files: edit the source of truth, run the script, commit the output. CI fails if
the two have drifted.

The source of truth is the registry the package ships, so the page cannot
describe a catalogue different from the one that scores.

Usage
-----
    python docs/build_catalogue.py           # write docs/clocks.qmd
    python docs/build_catalogue.py --check   # fail if it is stale (for CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TARGET = HERE / "clocks.qmd"

BANNER = ("<!-- GENERATED by docs/build_catalogue.py from the shipped registry.\n"
          "     Edit that script or the registry, not this file. -->")

TIER = {
    "A": "Coefficients ship with the package, or the clock is a formula with "
         "none to ship. Works offline, no network, no licence.",
    "B": "Catalogued, but no primary source for the coefficients has been "
         "established, so nothing is bundled. The metadata is real; the "
         "numbers are absent.",
    "C": "The architecture is implemented and tested; the coefficients are "
         "research-use-only and are not ours to distribute. Obtain a file and "
         "register it.",
}

HEAD = """---
title: "Clock catalogue"
subtitle: "All {n}, generated from the registry that scores them"
---

{banner}

This page is written from the registry the package ships, so it cannot describe
a catalogue different from the one that scores. Every column below is a field
the scoring code reads.

`scale_type` is the load-bearing one. It is not a label -- it decides which
downstream operations FALCONAge will perform, and asking for age acceleration
on a `pace_ratio` clock is refused rather than computed.

**{n} clocks**, registry schema `{schema}`.
"""

TAIL = """
## Querying it from code

::: {.panel-tabset}

### Python

```python
reg = fa.registry.load()
reg.filter(availability="A", scale_type="age_years")
reg.search("mortality")
reg.compatible_with(data)
reg.get("horvath2013")
```

### R

```r
list_clocks(tier = "A")
list_clocks(search = "mortality")
compatible_clocks(d)
clock_info("horvath2013")
```

:::
"""


def render() -> str:
    import falconage as fa

    reg = fa.registry.load()
    clocks = sorted(reg, key=lambda c: (c.availability, c.id))

    out = [HEAD.format(n=len(clocks), schema=reg.version, banner=BANNER)]
    for tier in ("A", "B", "C"):
        rows = [c for c in clocks if c.availability == tier]
        out.append(f"\n## Tier {tier} — {len(rows)} clocks\n")
        out.append(TIER[tier] + "\n")
        out.append("| Clock | Year | Predicts | Scale | Features | Platform |")
        out.append("|---|---:|---|---|---:|---|")
        for c in rows:
            plat = ", ".join(c.platform) or "—"
            out.append(f"| `{c.id}` | {c.year or '—'} | {c.name} | "
                       f"`{c.scale_type}` | {c.n_features or '—'} | {plat} |")
        out.append("")
    out.append(TAIL)
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if docs/clocks.qmd is out of date")
    args = ap.parse_args(argv)

    try:
        text = render()
    except ImportError:
        print("falconage is not importable; install it before generating the "
              "catalogue (pip install ./python)")
        return 1

    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale; run docs/build_catalogue.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)} ({text.count(chr(10)) + 1} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
