#!/usr/bin/env python3
"""Build the offline copies of the documentation: two PDFs and a markdown bundle.

WHY THESE EXIST. A documentation website is not something you can attach to a
thesis, read on a plane, cite a page of, or diff between releases. The three
artefacts here cover those cases, and every documentation build produces them so
they cannot fall behind the site they came from.

    FALCONAge-manual.pdf             the R reference manual, R CMD Rd2pdf
    FALCONAge-python-reference.pdf   the guides and Python API, one Quarto book
    FALCONAge-docs-markdown.zip      the whole thing as markdown, both languages

WHY EACH BUILDS INDEPENDENTLY. They need different toolchains -- LaTeX for the
first, Quarto and Typst for the second, pandoc for the third -- and a laptop
usually has some of them. A missing toolchain costs you that one artefact and
says so; it does not fail the run. CI has all three, so CI gets all three.

WHY THE PYTHON PDF IS A BOOK AND THE SITE IS NOT. Rendering a Quarto *website*
to PDF gives one PDF per page, which is not a manual. A book project over the
same source files gives a single document with a contents page and cross
references that resolve. So this generates a throwaway book config beside the
site config rather than making the site a book, which would change the site.

Usage
-----
    python docs/build_downloads.py --all
    python docs/build_downloads.py --manual --out docs/_site/downloads
    python docs/build_downloads.py --markdown
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GROUPS = HERE / "reference-groups.yml"
DEFAULT_OUT = HERE / "_site" / "downloads"

# The book's spine. Order is deliberate: what the thing is, how to use it, how to
# choose, then the API. The reference chapters are appended from whatever
# quartodoc generated, so a new section in reference-groups.yml appears here
# without editing this file.
FRONT = ["index.qmd", "guide/FALCONAge.qmd", "guide/clocks.qmd",
         "clocks.qmd", "gpu.md", "science.qmd", "architecture.qmd"]


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print("  $", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def have(tool: str) -> bool:
    return shutil.which(tool) is not None


# ---------------------------------------------------------------------------
# 1. the R reference manual
# ---------------------------------------------------------------------------
def build_manual(out: Path) -> Path:
    """`R CMD Rd2pdf` over r/, which is the layout CRAN itself publishes.

    Not pkgdown's HTML converted to PDF: this reads man/*.Rd directly, so it
    covers exactly the exported surface `?fn` covers, in the order and with the
    sectioning an R user already knows how to read.
    """
    if not have("R"):
        raise RuntimeError("R is not on PATH")
    target = out / "FALCONAge-manual.pdf"
    target.unlink(missing_ok=True)
    run(["R", "CMD", "Rd2pdf", "--force", "--no-preview", "--batch",
         f"--output={target}", str(ROOT / "r")], cwd=ROOT)
    return target


# ---------------------------------------------------------------------------
# 2. the Python reference as one PDF
# ---------------------------------------------------------------------------
def book_config(chapters: list[str]) -> str:
    site = yaml.safe_load(GROUPS.read_text(encoding="utf-8"))["site"]
    doc = {
        "project": {"type": "book", "output-dir": "_pdf_out"},
        "book": {
            "title": site["title"],
            "subtitle": " ".join(site["description"].split()),
            "author": "Bhagesh Hunakunti",
            "chapters": ["index.qmd"] + [c for c in chapters if c != "index.qmd"],
        },
        # Typst rather than LaTeX: it ships inside Quarto, so the PDF builds on
        # a runner with no TeX distribution and in about a tenth of the time.
        "format": {"typst": {"toc": True, "papersize": "a4",
                             "mainfont": "Libertinus Serif"}},
        # The reference pages are generated by quartodoc into reference/; the
        # book must not try to regenerate them.
        "quartodoc": None,
    }
    doc = {k: v for k, v in doc.items() if v is not None}
    return ("# GENERATED by docs/build_downloads.py. Throwaway: it exists only for\n"
            "# the duration of a PDF build and is removed afterwards.\n"
            + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True))


def reference_chapters() -> list[str]:
    ref = HERE / "reference"
    if not ref.is_dir():
        return []
    index = ref / "index.qmd"
    pages = sorted(p for p in ref.glob("*.qmd") if p != index)
    return ([str(index.relative_to(HERE)).replace("\\", "/")] if index.exists() else []) \
        + [str(p.relative_to(HERE)).replace("\\", "/") for p in pages]


def build_python_pdf(out: Path) -> Path:
    if not have("quarto"):
        raise RuntimeError("quarto is not on PATH")
    chapters = [c for c in FRONT if (HERE / c).exists()] + reference_chapters()
    if len(chapters) < 2:
        raise RuntimeError("nothing to bind: run quartodoc first so reference/ exists")

    cfg = HERE / "_quarto-pdf.yml"
    cfg.write_text(book_config(chapters), encoding="utf-8", newline="\n")
    try:
        # A profile would be tidier, but Quarto resolves the project TYPE from
        # the base config before profiles are applied, so a website cannot
        # become a book that way. A separate config file can.
        run(["quarto", "render", "--config", cfg.name], cwd=HERE)
        built = next((HERE / "_pdf_out").glob("*.pdf"))
        target = out / "FALCONAge-python-reference.pdf"
        shutil.copyfile(built, target)
        return target
    finally:
        cfg.unlink(missing_ok=True)
        shutil.rmtree(HERE / "_pdf_out", ignore_errors=True)


# ---------------------------------------------------------------------------
# 3. everything as markdown
# ---------------------------------------------------------------------------
def build_markdown(out: Path) -> Path:
    """The site as GitHub-flavoured markdown, both languages in one zip.

    The Quarto half renders straight to gfm. The R half is converted from
    pkgdown's HTML with pandoc rather than from the .Rd sources, because Rd is
    a TeX dialect and every direct converter for it loses the usage block --
    which is the part of a help page anybody actually reads.
    """
    if not have("quarto"):
        raise RuntimeError("quarto is not on PATH")
    stage = HERE / "_md_out"
    shutil.rmtree(stage, ignore_errors=True)

    chapters = [c for c in FRONT if (HERE / c).exists()] + reference_chapters()
    cfg = HERE / "_quarto-md.yml"
    doc = {"project": {"type": "book", "output-dir": "_md_out"},
           "book": {"title": "FALCONAge", "chapters": chapters},
           "format": {"gfm": {"toc": True}}}
    cfg.write_text("# GENERATED by docs/build_downloads.py; removed after the build.\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
                   encoding="utf-8", newline="\n")
    try:
        run(["quarto", "render", "--config", cfg.name], cwd=HERE)
    finally:
        cfg.unlink(missing_ok=True)

    # The R side, from pkgdown's output if the site has been built.
    r_html = sorted((HERE / "r" / "reference").glob("*.html"))
    if r_html and have("pandoc"):
        r_md = stage / "r-reference"
        r_md.mkdir(parents=True, exist_ok=True)
        for page in r_html:
            if page.name == "index.html":
                continue
            run(["pandoc", "-f", "html", "-t", "gfm", "--wrap=none",
                 "-o", str(r_md / f"{page.stem}.md"), str(page)])
    else:
        print("  (no pkgdown output or no pandoc: skipping the R half)")

    for extra in ("README.md", "CITATION.cff"):
        src = ROOT / extra
        if src.exists():
            shutil.copyfile(src, stage / extra)

    target = out / "FALCONAge-docs-markdown.zip"
    target.unlink(missing_ok=True)
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as z:
        for p in sorted(stage.rglob("*")):
            if p.is_file():
                z.write(p, p.relative_to(stage).as_posix())
    shutil.rmtree(stage, ignore_errors=True)
    return target


BUILDERS = {"manual": build_manual, "python-pdf": build_python_pdf,
            "markdown": build_markdown}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    for name in BUILDERS:
        ap.add_argument(f"--{name}", action="store_true")
    ap.add_argument("--all", action="store_true", help="every artefact")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--strict", action="store_true",
                    help="exit non-zero if any requested artefact failed")
    args = ap.parse_args(argv)

    wanted = [n for n in BUILDERS if args.all or getattr(args, n.replace("-", "_"))]
    if not wanted:
        ap.error("nothing requested; pass --all or one of "
                 + ", ".join(f"--{n}" for n in BUILDERS))

    args.out.mkdir(parents=True, exist_ok=True)
    failed = []
    for name in wanted:
        print(f"\n[{name}]")
        try:
            path = BUILDERS[name](args.out)
            print(f"  wrote {path.relative_to(ROOT)}  "
                  f"({path.stat().st_size / 1e6:.1f} MB)")
        except Exception as exc:
            print(f"  SKIPPED: {exc}")
            failed.append(name)

    made = [n for n in wanted if n not in failed]
    print(f"\n{len(made)}/{len(wanted)} artefact(s) built into "
          f"{args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out}")
    if failed:
        print("skipped: " + ", ".join(failed))
    return 1 if (failed and args.strict) else 0


if __name__ == "__main__":
    sys.exit(main())
