#!/usr/bin/env python3
"""Emit ``docs/references.qmd`` from ``docs/references.yml``, and check the citations.

WHY ONE LIST AND NOT ONE PER PAGE. The bibliography used to sit at the bottom of
science.qmd, numbered 1 to 64. Nothing else could cite it: a source used on the
landing page and in the guide was written out in prose in both places, so the
same paper appeared under three different descriptions and no number meant
anything outside the page it was on. Pages now cite ``[[7]](references.qmd#ref-7)``
and 7 is 7 everywhere, including in the PDF, where the same list is bound as its
own chapter.

WHY THE ORDER IS FROZEN. A citation number is a reference to a position in this
file. Inserting an entry in the middle would silently renumber every citation
after it, and nothing about the rendered page would look wrong. Entries are
appended. ``--check`` enforces the invariant that matters: every number a page
cites exists.

Usage
-----
    python docs/build_references.py           # write docs/references.qmd
    python docs/build_references.py --check   # fail if stale, or a citation dangles
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = HERE / "references.yml"
PAGE = HERE / "references.qmd"

BANNER = ("<!-- GENERATED by docs/build_references.py from docs/references.yml.\n"
          "     Edit the YAML, not this file. -->")

HEAD = f"""---
title: "References"
subtitle: "Every source the documentation cites, numbered once"
---

{BANNER}

Citations across this site are numbers in square brackets and every one of them
points here. The numbering is global rather than per page, so a source keeps its
number wherever it is cited, and the same list is bound into the PDF as its own
chapter.

Where a source is available at a stable identifier the entry links to it. Some
of these are preprints and are cited as preprints on purpose: the field moves
faster than journal review, and a claim resting on one is worth knowing about.

"""

#: `[[42]](references.qmd#ref-42)` and the guide-relative `../references.qmd#ref-42`.
#: Both halves are captured so a page that disagrees with itself, linking to
#: #ref-7 under the label [8], is caught rather than rendered.
CITATION = re.compile(r"\[\[(\d+)\]\]\((?:\.\./)?references\.qmd#ref-(\d+)\)")


def load() -> list[dict]:
    spec = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    groups = spec["groups"]
    seen = [e["n"] for g in groups for e in g["entries"]]
    if seen != list(range(1, len(seen) + 1)):
        raise SystemExit(
            f"{SOURCE.name}: entries must be numbered 1..{len(seen)} in order, "
            "because a citation number is a position in this file. Append, never "
            "insert.")
    return groups


def render(groups: list[dict]) -> str:
    out = [HEAD]
    for g in groups:
        out.append(f"## {g['title']}\n")
        for e in g["entries"]:
            n, text = e["n"], e["text"]
            link = ""
            if e.get("doi"):
                # The identifier is about to be rendered as a link, so drop the
                # bare `doi:10.…` the prose carries or the entry prints it twice.
                text = re.sub(r"\s*doi:\s*" + re.escape(e["doi"]) + r"[.,]?", "",
                              text).rstrip()
                link = f" [https://doi.org/{e['doi']}](https://doi.org/{e['doi']})"
            elif e.get("url"):
                text = text.replace(e["url"], "").rstrip().rstrip(".,") + "."
                link = f" [{e['url']}]({e['url']})"
            # An explicit anchor rather than a Quarto list, because the citation
            # links target #ref-N and an ordered list numbers itself with no id
            # to aim at.
            out.append(f"[{n}]{{#ref-{n}}}. {text}{link}\n")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def cited() -> dict[Path, list[tuple[int, int]]]:
    """Every citation in the hand-written pages, by file."""
    found: dict[Path, list[tuple[int, int]]] = {}
    for p in sorted(HERE.glob("*.qmd")) + sorted(HERE.glob("guide/*.qmd")):
        if p == PAGE:
            continue
        hits = [(int(a), int(b))
                for a, b in CITATION.findall(p.read_text(encoding="utf-8"))]
        if hits:
            found[p] = hits
    return found


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the page is stale or a citation dangles")
    args = ap.parse_args(argv)

    groups = load()
    n = sum(len(g["entries"]) for g in groups)
    text = render(groups)

    bad: list[str] = []
    for path, hits in cited().items():
        rel = path.relative_to(ROOT)
        for label, target in hits:
            if label != target:
                bad.append(f"{rel}: [{label}] links to #ref-{target}")
            elif not 1 <= target <= n:
                bad.append(f"{rel}: [{target}] has no entry; the list ends at {n}")

    if args.check:
        stale = not PAGE.exists() or PAGE.read_text(encoding="utf-8") != text
        if stale:
            print("stale, regenerate with docs/build_references.py:")
            print(f"  {PAGE.relative_to(ROOT)}")
        for b in bad:
            print(b)
        if stale or bad:
            return 1
        total = sum(len(h) for h in cited().values())
        print(f"references.qmd is current; {total} citation(s) across "
              f"{len(cited())} page(s) all resolve within 1..{n}")
        return 0

    if bad:
        print("citations that do not resolve:")
        for b in bad:
            print(f"  {b}")
        return 1

    PAGE.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {PAGE.relative_to(ROOT)}: {n} entries in {len(groups)} group(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
