#!/usr/bin/env python3
"""Assert the documentation still says what v1.1.0 actually is.

WHY THIS EXISTS AS A SCRIPT RATHER THAN A REVIEW. Seven documentation defects
were reported and fixed by hand: the main page did not name the v1.1 inputs, the
catalogue linked no papers, the architecture page still called itself v1.0, the
getting-started page mixed commands with their output in one fence, the
choosing-a-clock page did not route every clock, the availability column asked
for half the page to print one letter, and the Python/R parity table claimed
features were missing from Python that were present under another name.

Every one of those is the kind of defect that comes back. Three of the pages are
regenerated by ``build_catalogue.py`` and ``build_docs.py``, so a change to a
generator can undo a hand fix silently; the rest rot the next time a feature
lands. A fixed defect with no test is a defect on a timer.

So each is restated here as a property of the files, checked against the running
package rather than against a remembered answer.

Usage
-----
    python docs/check_docs_complete.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "python" / "src"))

import falconage as fa                      # noqa: E402
from falconage import registry              # noqa: E402

#: Inputs v1.1 added. Naming them on the landing page is the difference between
#: a reader knowing the tool reads their data and assuming it does not.
V11_INPUTS = ("olink", "somascan", "nanopore", "bedmethyl", "rna-seq", "idat")

DASHES = {"—", "–", "-", ""}


def _generated(path: Path, marker: str) -> str:
    text = path.read_text(encoding="utf-8")
    return text.split(f"BEGIN GENERATED: {marker}")[1].split("END GENERATED")[0]


def main() -> int:
    reg = registry.load()
    all_ids = {c.id for c in reg}
    problems: list[str] = []

    index = (ROOT / "docs" / "index.qmd").read_text(encoding="utf-8").lower()
    arch = (ROOT / "docs" / "architecture.qmd").read_text(encoding="utf-8")
    cat = (ROOT / "docs" / "clocks.qmd").read_text(encoding="utf-8")
    guide = (ROOT / "docs" / "guide" / "FALCONAge.qmd").read_text(encoding="utf-8")
    choose = ROOT / "docs" / "guide" / "clocks.qmd"
    r_readme = ROOT / "r" / "README.md"

    # 1 -- the landing page names what the package can read.
    missing = [w for w in V11_INPUTS if w not in index]
    if missing:
        problems.append(
            f"docs/index.qmd does not mention {', '.join(missing)}. A reader with "
            "that data cannot tell the package accepts it.")

    # 2 -- every catalogued clock links to its paper.
    rows = re.findall(r"^\| `([a-z0-9]+)` \|", cat, re.M)
    linked = re.findall(
        r"^\| `([a-z0-9]+)` \|.*\[[^\]]+\]\(https://doi\.org/", cat, re.M)
    if set(rows) != set(linked):
        unlinked = sorted(set(rows) - set(linked))[:8]
        problems.append(
            f"{len(set(rows) - set(linked))} clock(s) in docs/clocks.qmd carry no "
            f"paper link: {unlinked}")
    if set(rows) != all_ids:
        problems.append(
            f"docs/clocks.qmd lists {len(rows)} clocks, the registry has {len(all_ids)}")

    # 3 -- the architecture page describes the version that ships.
    if f"**Current as of v{fa.__version__}.**" not in arch:
        problems.append(
            f"docs/architecture.qmd does not declare itself current as of "
            f"v{fa.__version__}; it is the page most likely to describe a past release")

    # 4 -- outputs are marked as outputs, never pasted into a command fence.
    if "::: {.falcon-output}" not in guide:
        problems.append(
            "docs/guide/FALCONAge.qmd has no .falcon-output block; command output "
            "belongs in one so a reader does not paste it into a terminal")
    for fence in re.findall(r"```(?:bash|sh)\n(.*?)```", guide, re.S):
        has_cmd = re.search(r"^\s*(docker|falconage|pip|git|Rscript|python)", fence, re.M)
        has_out = re.search(r"^(INFO|WARNING|ERROR|FalconData|#>|\s*\S+\s+\d+\.\d+)",
                            fence, re.M)
        if has_cmd and has_out:
            problems.append(
                "a bash fence in docs/guide/FALCONAge.qmd mixes commands with their "
                f"output: {fence.strip().splitlines()[0][:60]!r}")

    # 5 -- every catalogued clock is routed by the question it answers.
    block = _generated(choose, "by-question")
    named = set(re.findall(r"`([a-z0-9]+)`", block)) & all_ids
    hidden = sum(int(m) for m in re.findall(r"and (\d+) more", block))
    if named and (len(named) + hidden) != len(all_ids):
        problems.append(
            f"docs/guide/clocks.qmd routes {len(named) + hidden} clocks, the "
            f"registry has {len(all_ids)}. A clock nobody can find is a clock "
            "nobody can use.")

    # 6 -- the availability column is a letter, and should be sized like one.
    tier = _generated(choose, "tiers")
    sep = next((ln for ln in tier.splitlines()
                if "-" in ln and set(ln.strip()) <= set("|:- ")), None)
    if sep is None:
        problems.append("docs/guide/clocks.qmd tier table has no separator row")
    else:
        widths = [len(c.strip()) for c in sep.strip().strip("|").split("|")]
        share = widths[0] / sum(widths)
        if share > 0.15:
            problems.append(
                f"the tier column asks for {share:.0%} of the table width to print "
                f"one letter (dash counts {widths}). Pandoc sizes columns by the "
                "dashes in the separator row.")

    # 7 -- the parity table must not claim Python lacks something it has.
    parity = _generated(r_readme, "api-map")
    for line in parity.splitlines():
        if not line.startswith("|") or set(line) <= set("|-: "):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 3:
            continue
        r_name, py_name = cells[1].strip("`*"), cells[2].strip("`*")
        if py_name not in DASHES or r_name in DASHES:
            continue
        stem = r_name.split("(")[0]
        if hasattr(fa, stem) or hasattr(fa.preprocess, stem):
            problems.append(
                f"the parity table says Python lacks {stem!r}, but it exists. "
                "Pair it in docs/build_docs.py METHODS, or explain it in R_ONLY.")

    # 8 -- no generated directory is in git.
    #
    # Every path here is written by a build step that CI runs before rendering,
    # so a committed copy is dead weight that also goes stale. `docs/figures/`
    # held a second copy of all 26 gallery PNGs, 21 of which had drifted from
    # the tracked originals, so the website was serving older figures than the
    # test run produced. `docs/reference/` held 115 files of quartodoc output.
    #
    # Both were already listed in .gitignore -- with the explanation on the same
    # line as the pattern, which git does not treat as a comment, so all three
    # of those rules matched the literal string "docs/figures/    # staged..."
    # and had never done anything. A rule that silently does nothing is worse
    # than no rule, so this asserts the outcome instead of trusting the pattern.
    # Positively confirm git answered before trusting a clean result. A check
    # that cannot run must not report a pass -- silently skipping is the same
    # failure mode as the broken ignore rules it exists to catch.
    import subprocess

    def _tracked(path: str) -> int | None:
        try:
            r = subprocess.run(["git", "ls-files", "--error-unmatch", "--", path],
                               cwd=ROOT, capture_output=True, text=True, timeout=30)
        except Exception:
            return None
        if r.returncode != 0 and "did not match" not in (r.stderr or ""):
            return None                 # git itself failed, not "no such files"
        return len([ln for ln in r.stdout.splitlines() if ln.strip()])

    probe = _tracked("README.md")       # a file that is certainly tracked
    if probe is None or probe == 0:
        problems.append(
            "cannot ask git which files are tracked, so the check that no "
            "generated directory is committed did not run. Reporting this "
            "rather than passing: an unrunnable check is not a clean one.")
    else:
        for gen in ("docs/figures", "docs/reference", "docs/r", "docs/_site",
                    "docs/site_libs"):
            n = _tracked(gen)
            if n:
                problems.append(
                    f"{n} generated file(s) under {gen}/ are tracked by git. They "
                    f"are rebuilt by CI before every render; untrack with "
                    f"`git rm -r --cached {gen}`.")

        # Rendered pages, which are files rather than a directory and so were
        # not covered above. Quarto writes each one into docs/ during a render
        # and moves it to docs/_site/ at the end; a `git add -A` that lands
        # while a render is running captures the intermediate. Twenty-five were
        # committed exactly that way. Two .html files here are genuinely source
        # -- the include-after-body fragments -- so the check is a subtraction
        # rather than a blanket ban.
        SOURCE_HTML = {"docs/cite-copy.html", "docs/table-scroll.html"}
        try:
            listed = subprocess.run(
                ["git", "ls-files", "--", "docs/*.html", "docs/guide/*.html"],
                cwd=ROOT, capture_output=True, text=True, timeout=30,
                check=True).stdout.split()
        except Exception:
            listed = []
        stray = sorted(set(listed) - SOURCE_HTML)
        if stray:
            problems.append(
                f"{len(stray)} rendered page(s) are tracked by git: "
                f"{stray[:4]}. Quarto writes these into docs/ mid-render and "
                f"moves them to docs/_site/; only "
                f"{', '.join(sorted(SOURCE_HTML))} are source. Untrack with "
                f"`git rm --cached {stray[0]}`.")

    # 9 -- the GPU page's coverage table agrees with the code.
    #
    # docs/gpu.md tells a reader which model classes `device="cuda"` reaches.
    # For a year it implied all of them, and three shipping clocks plus two
    # architectures ignored the device entirely. That was invisible because
    # nothing tied the sentence to the classes. The declaration is one attribute
    # now, so the page can be checked against it rather than reviewed.
    gpu_md = (ROOT / "docs" / "gpu.md").read_text(encoding="utf-8")
    classes = {"LinearClock": fa.models.LinearClock,
               "PCLinearClock": fa.models.PCLinearClock,
               "AggregationClock": fa.models.AggregationClock,
               "NeuralClock": fa.models.NeuralClock,
               "ClinicalClock": fa.models.ClinicalClock}
    for name, cls in classes.items():
        row = next((ln for ln in gpu_md.splitlines()
                    if ln.startswith(f"| `{name}`")), None)
        if row is None:
            problems.append(
                f"docs/gpu.md has no coverage row for {name}. A model class a "
                "reader cannot look up is one they will assume uses the device.")
            continue
        says_no = "**no" in row.lower()
        if says_no != bool(getattr(cls, "CPU_ONLY", False)):
            problems.append(
                f"docs/gpu.md says {name} "
                f"{'declines' if says_no else 'reaches'} the device; the class "
                f"says {'CPU_ONLY' if not says_no else 'it uses the spec'}.")

    # 10 -- the architecture page's list of shipped workflows is the real one.
    #
    # Section 12.1 specifies nine workflows and four exist. That is fine and
    # said so, in a note listing the four by name. What is not fine is the note
    # going stale: a reader checking which CI actually runs would then be
    # reading a second wrong list instead of the first. The specification table
    # underneath is deliberately not checked; it is the design, and the note is
    # what reconciles it.
    # The note is a blockquote, so its table rows begin "> |" and the
    # specification table's rows begin "|". That prefix is the whole
    # discrimination, and it is why the two can share a section safely.
    on_disk = {p.name for p in (ROOT / ".github" / "workflows").glob("*.y*ml")}
    note = arch.split("### 12.1 Workflows")[1].split("### 12.2")[0]
    claimed = set(re.findall(r"^> \| `([A-Za-z0-9_-]+\.ya?ml)` \|", note, re.M))
    if not claimed:
        problems.append(
            "docs/architecture.qmd 12.1 has no note listing the workflows that "
            "actually ship. The table under it is the design, and it specifies "
            "more than exists.")
    elif claimed != on_disk:
        problems.append(
            f"docs/architecture.qmd 12.1 says these workflows ship: "
            f"{sorted(claimed)}; .github/workflows holds {sorted(on_disk)}.")

    # 11 -- pulling the published image is offered before building it.
    #
    # Both images are on Docker Hub as bhagesh/falconage. A page that opens
    # with `docker build` sends a reader through a ten-minute build and a git
    # clone to obtain a thing they could have pulled in two minutes, and most
    # readers do what the first code block says. The build stays documented,
    # because building from source is the point of shipping a Dockerfile; it
    # just goes second.
    #
    # Only the two published images are covered. Dockerfile.testdata, .dev,
    # .docs and .responsive build local helper images that are not on any
    # registry, and telling somebody to pull one would be worse than the
    # problem this fixes.
    import subprocess as _sp

    try:
        tracked = _sp.run(["git", "ls-files", "--", "*.md", "*.qmd"], cwd=ROOT,
                          capture_output=True, text=True, timeout=30,
                          check=True).stdout.split()
    except Exception:
        tracked = []
        problems.append(
            "cannot ask git which files are tracked, so the pull-before-build "
            "check did not run.")

    for rel in tracked:
        if rel.startswith(("docs/reference/", "docs/r/", "docs/_site/")) \
                or rel == "docs/architecture.qmd":
            continue
        lines = (ROOT / rel).read_text(encoding="utf-8",
                                       errors="ignore").splitlines()
        for i, ln in enumerate(lines):
            m = re.search(r"docker build .*-t (bhagesh/falconage:\S+)", ln)
            if not m:
                continue
            image = m.group(1)
            window = "\n".join(lines[max(0, i - 14):i])
            if f"docker pull {image}" not in window:
                problems.append(
                    f"{rel}:{i + 1}: `docker build` for {image} with no "
                    f"`docker pull {image}` in the 14 lines above it. The "
                    f"image is published; offer the pull first.")

    if problems:
        print(f"{len(problems)} documentation defect(s):")
        for p in problems:
            print(f"  - {p}")
        return 1

    print(f"documentation is current for v{fa.__version__}: the landing page names "
          f"every input, all {len(all_ids)} clocks are linked and routed, the "
          "architecture page is on this release, output is marked as output, the "
          "tier column is sized for a letter, the parity table claims no false "
          "gap, the GPU page's coverage table matches what the model classes "
          f"declare, the architecture page names the {len(on_disk)} workflows "
          "that exist, and every documented build of a published image offers "
          "the pull first")
    return 0


if __name__ == "__main__":
    sys.exit(main())
